# Site settings
title: Central Ohio Mesh
author: Central Ohio Mesh
description: Welcome to Central Ohio Mesh, the Meshtastic local group for the Columbus, Ohio metro area.
baseurl: "" # Leave blank if deploying to root. Otherwise, use /subpath for GitHub Pages.
url: "" # Fill this in if you have a custom domain (e.g., https://centralohiomesh.com).

# Theme and appearance
theme: jekyll-theme-hacker
logo: /assets/img/com_logo_web.png
show_downloads: false

# Social links (Optional, customize if needed)
social:
  discord: https://discord.gg/B6fuujsHJu

# Custom navigation links
nav_links:
  - name: Home
    url: /https://meshcolumb.us/
  - name: Useful Links
    url: /useful-links/
  - name: Discord
    url: https://discord.gg/B6fuujsHJu
  - name: About
    url: /about/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Deployment settings
# Uncomment and configure these if using GitHub Pages
# github:
#   repository: your-username/your-repo
